"""Test metprint
"""
from metprint import (
	LogType,
	Logger,
	MeterpreterFormatter,
	FHFormatter,
	FHNFFormatter,
	PythonFormatter,
	ColorLogFormatter,
	PrintTagsFormatter,
	XaFormatter,
	LamuFormatter,
	CustomFormatter,
)


print("#########################")
print("#      Meterpreter      #")
print("#########################")
metLogger = Logger(MeterpreterFormatter())
metLogger.logPrint("none", LogType.NONE)
metLogger.logPrint("bold", LogType.BOLD)
metLogger.logPrint("italic", LogType.ITALIC)
metLogger.logPrint("header", LogType.HEADER)
metLogger.logPrint("debug", LogType.DEBUG)
metLogger.logPrint("info", LogType.INFO)
metLogger.logPrint("success", LogType.SUCCESS)
metLogger.logPrint("warning", LogType.WARNING)
metLogger.logPrint("error", LogType.ERROR)
metLogger.logPrint("critical", LogType.CRITICAL)


print("#########################")
print("#          FH           #")
print("#########################")
fhLogger = Logger(FHFormatter())
fhLogger.logPrint("none", LogType.NONE)
fhLogger.logPrint("bold", LogType.BOLD)
fhLogger.logPrint("italic", LogType.ITALIC)
fhLogger.logPrint("header", LogType.HEADER)
fhLogger.logPrint("debug", LogType.DEBUG)
fhLogger.logPrint("info", LogType.INFO)
fhLogger.logPrint("success", LogType.SUCCESS)
fhLogger.logPrint("warning", LogType.WARNING)
fhLogger.logPrint("error", LogType.ERROR)
fhLogger.logPrint("critical", LogType.CRITICAL)

print("#########################")
print("#         FHNF          #")
print("#########################")
fhnfLogger = Logger(FHNFFormatter())
fhnfLogger.logPrint("none", LogType.NONE)
fhnfLogger.logPrint("bold", LogType.BOLD)
fhnfLogger.logPrint("italic", LogType.ITALIC)
fhnfLogger.logPrint("header", LogType.HEADER)
fhnfLogger.logPrint("debug", LogType.DEBUG)
fhnfLogger.logPrint("info", LogType.INFO)
fhnfLogger.logPrint("success", LogType.SUCCESS)
fhnfLogger.logPrint("warning", LogType.WARNING)
fhnfLogger.logPrint("error", LogType.ERROR)
fhnfLogger.logPrint("critical", LogType.CRITICAL)

print("#########################")
print("#        Python         #")
print("#########################")
pythonLogger = Logger(PythonFormatter())
pythonLogger.logPrint("none", LogType.NONE)
pythonLogger.logPrint("bold", LogType.BOLD)
pythonLogger.logPrint("italic", LogType.ITALIC)
pythonLogger.logPrint("header", LogType.HEADER)
pythonLogger.logPrint("debug", LogType.DEBUG)
pythonLogger.logPrint("info", LogType.INFO)
pythonLogger.logPrint("success", LogType.SUCCESS)
pythonLogger.logPrint("warning", LogType.WARNING)
pythonLogger.logPrint("error", LogType.ERROR)
pythonLogger.logPrint("critical", LogType.CRITICAL)

print("#########################")
print("#       ColorLog        #")
print("#########################")
colorLogLogger = Logger(ColorLogFormatter())
colorLogLogger.logPrint("none", LogType.NONE)
colorLogLogger.logPrint("bold", LogType.BOLD)
colorLogLogger.logPrint("italic", LogType.ITALIC)
colorLogLogger.logPrint("header", LogType.HEADER)
colorLogLogger.logPrint("debug", LogType.DEBUG)
colorLogLogger.logPrint("info", LogType.INFO)
colorLogLogger.logPrint("success", LogType.SUCCESS)
colorLogLogger.logPrint("warning", LogType.WARNING)
colorLogLogger.logPrint("error", LogType.ERROR)
colorLogLogger.logPrint("critical", LogType.CRITICAL)

print("#########################")
print("#       PrintTags       #")
print("#########################")
printTagsLogger = Logger(PrintTagsFormatter())
printTagsLogger.logPrint("none", LogType.NONE)
printTagsLogger.logPrint("bold", LogType.BOLD)
printTagsLogger.logPrint("italic", LogType.ITALIC)
printTagsLogger.logPrint("header", LogType.HEADER)
printTagsLogger.logPrint("debug", LogType.DEBUG)
printTagsLogger.logPrint("info", LogType.INFO)
printTagsLogger.logPrint("success", LogType.SUCCESS)
printTagsLogger.logPrint("warning", LogType.WARNING)
printTagsLogger.logPrint("error", LogType.ERROR)
printTagsLogger.logPrint("critical", LogType.CRITICAL)

print("#########################")
print("#          Xa           #")
print("#########################")
xaLogger = Logger(XaFormatter())
xaLogger.logPrint("none", LogType.NONE)
xaLogger.logPrint("bold", LogType.BOLD)
xaLogger.logPrint("italic", LogType.ITALIC)
xaLogger.logPrint("header", LogType.HEADER)
xaLogger.logPrint("debug", LogType.DEBUG)
xaLogger.logPrint("info", LogType.INFO)
xaLogger.logPrint("success", LogType.SUCCESS)
xaLogger.logPrint("warning", LogType.WARNING)
xaLogger.logPrint("error", LogType.ERROR)
xaLogger.logPrint("critical", LogType.CRITICAL)

print("#########################")
print("#         Lamu          #")
print("#########################")
lamuLogger = Logger(LamuFormatter())
lamuLogger.logPrint("none", LogType.NONE)
lamuLogger.logPrint("bold", LogType.BOLD)
lamuLogger.logPrint("italic", LogType.ITALIC)
lamuLogger.logPrint("header", LogType.HEADER)
lamuLogger.logPrint("debug", LogType.DEBUG)
lamuLogger.logPrint("info", LogType.INFO)
lamuLogger.logPrint("success", LogType.SUCCESS)
lamuLogger.logPrint("warning", LogType.WARNING)
lamuLogger.logPrint("error", LogType.ERROR)
lamuLogger.logPrint("critical", LogType.CRITICAL)

print("#########################")
print("#        Custom         #")
print("#########################")
customLogger = Logger(CustomFormatter())
customLogger.logPrint("none", LogType.NONE)
customLogger.logPrint("bold", LogType.BOLD)
customLogger.logPrint("italic", LogType.ITALIC)
customLogger.logPrint("header", LogType.HEADER)
customLogger.logPrint("debug", LogType.DEBUG)
customLogger.logPrint("info", LogType.INFO)
customLogger.logPrint("success", LogType.SUCCESS)
customLogger.logPrint("warning", LogType.WARNING)
customLogger.logPrint("error", LogType.ERROR)
customLogger.logPrint("critical", LogType.CRITICAL)
